// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountPageController from "./account_page_controller"
application.register("account-page", AccountPageController)

import InputChildInfoController from "./input_child_info_controller"
application.register("input-child-info", InputChildInfoController)

import ResultsController from "./results_controller"
application.register("results", ResultsController)
