// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus";
import { definitionsFromContext } from "@hotwired/stimulus-webpack-helpers";
const application = Application.start();

// Configure Stimulus development experience
application.debug = false;
window.Stimulus = application;

const context = require.context("../controllers", true, /_controller\.js$/);

application.load(definitionsFromContext(context));
