---
- name: Include encrypted secrets
  include_vars:
    file: vars/secrets.yml

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-macOs.yml
  when: ansible_os_family == 'Darwin'
