---
- name: Ensure Homebrew is installed
  shell: |
    /bin/bash -c "$(curl -fsSl https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  become: false

- name: Update Homebrew history
  command: brew update
  register: brew_update_result
  become: false

- name: Install PostgreSQL {{ postgres_version }}
  homebrew:
   name: postgresql@{{ postgres_version }}
   state: present
  become: false

- name: Add PostgreSQL binary PATH
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'export PATH="/usr/local/opt/postgresql@{{ postgres_version }}/bin:$PATH"'
    state: present
    create: true

- name: Reload shell configuration to apply PATH changes
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh

- name: Start  PostgreSQL {{ postgres_version }} service
  command: brew services start postgresql@{{ postgres_version }}
  ignore_errors: true
  become: false

# TODO: install psycopg2-binary, create user and database

