---
- name: Install PostgreSQL via Homebrew
  shell: |
    brew install postgresql@12
    brew services stop postgresql@12
    brew services start postgresql@12
    PG_BIN_PATH=$(brew --prefix postgresql@12)/bin
    echo "export PATH=$PG_BIN_PATH:$PATH" >> ~/.zshrc
    echo "export PATH=$PG_BIN_PATH:$PATH" >> ~/.bashrc
    source ~/.zshrc || source ~/.bashrc
    $PG_BIN_PATH/psql --version
    brew --prefix postgresql@12
  become: false

- name: Create PostgreSQL user and database
  shell: |
    PG_BIN_PATH="/opt/homebrew/opt/postgresql@12/bin"

    DB_USER="postgres"
    DB_NAME_TEST="zero_waste_test"
    DB_NAME_DEV="zero_waste_development"

    if ! $PG_BIN_PATH/psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1; then
      $PG_BIN_PATH/createuser -s $DB_USER
    fi

    if ! $PG_BIN_PATH/psql -lqt | cut -d \| -f 1 | grep -qw $DB_NAME_TEST; then
      $PG_BIN_PATH/createdb -O $DB_USER $DB_NAME_TEST
    fi

    if ! $PG_BIN_PATH/psql -lqt | cut -d \| -f 1 | grep -qw $DB_NAME_DEV; then
      $PG_BIN_PATH/createdb -O $DB_USER $DB_NAME_DEV
    fi
  become: false
