comment:
  layout: "diff,flags,tree,betaprofiling"
  show_critical_paths: true

profiling:
  fixes:
    # you may need to add fixes with the full directory
    # up to the repository name on the left side
    # with respect to the environment running
    # e.g. - "/home/runner/src/ownername/reponame::"
    - "/home/runner/work/ZeroWaste/ZeroWaste::"
