version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - DATABASE_URL
    depends_on:
      - postgres
      - redis
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    env_file: .env
    links:
      - postgres
      - redis
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"

  postgres:
    image: postgres:12.1
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env.db

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file: .env.db

volumes:
  db_data:
  redis_data:
