---
- name: Ensure Homebrew is installed
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  become: false

- name: Install dependencies
  homebrew:
   name: "{{ item }}"
   state: present
  with_items: 
    - gpg
    - gnupg
    - curl
    - openssl
    - readline
    - libyaml
    - zlib
  become: false

- name: Install RVM
  shell: |
    \curl -sSL https://get.rvm.io | bash -s stable
  args: 
   creates: /usr/local/rvm/bin/rvm

- name: Add RVM to PATH
  shell: |
    echo 'source /usr/local/rvm/scripts/rvm' >> ~/.bash_profile
    source ~/.bash_profile

- name: Install Ruby
  shell: |
    source /usr/local/rvm/scripts/rvm && rvm install {{ rvm1_rubies }}
  environment: 
   rvm1_rubies: "{{ rvm1_rubies }}"

- name: Set default Ruby version
  shell: |
    source /usr/local/rvm/scripts/rvm && rvm use {{ rvm1_rubies }} --default
  environment: 
   rvm1_default_ruby_version: "{{ rvm1_default_ruby_version }}"

- name: Install bundler
  shell: |
    source /usr/local/rvm/scripts/rvm && gem install bundler

- name: Install Rails
  shell: |
    source /usr/local/rvm/scripts/rvm && gem install rails -v {{ rails_version }}
  environment:
    rails_version: "{{ rails_version }}"

- name: Get the username
  become: false
  local_action: command whoami
  register: username_on_the_host

- name: Run bundle install with Gemfile
  shell: |
    source /usr/local/rvm/scripts/rvm && rvm use {{ rvm1_rubies }} do bundle install --gemfile Gemfile
  args:
   chdir: "/Users/{{ username_on_the_host.stdout }}/ZeroWaste/"
  become_user: "{{ username_on_the_host.stdout }}"

- name: Run rake db:migrate
  shell: |
    source /usr/local/rvm/scripts/rvm && rvm use {{ rvm1_rubies }} do rake db:migrate
    args:
    chdir: "/Users/{{ username_on_the_host.stdout }}/ZeroWaste/"
  become_user: "{{ username_on_the_host.stdout }}"