---
openapi: 3.0.1
info:
  title: API V2
  version: v2
paths:
  "/calculators/{slug}/calculate":
    post:
      summary: calculate calculator
      tags:
      - Calculators by constructor
      description: Calculate calculator based on user input. Available calculators
        can be revealed by GET /calculators
      parameters:
      - name: slug
        in: path
        description: slug of the calculator
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful (example formula is 'first_value+second_value+third_value')
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    label:
                      type: string
                    result:
                      type: string
                    unit:
                      type: string
                    relation:
                      type: string
                      nullable: true
                  required:
                  - label
                  - result
                  - unit
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      third_value:
                        type: string
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_value:
                  type: number
                  example: 1
                  description: First value
                second_value:
                  type: number
                  example: 2
                  description: Second value
                third_value:
                  type: number
                  example: 3
                  description: Third value
  "/calculators":
    get:
      summary: list calculators
      tags:
      - Calculators by constructor
      description: List all calculators available in the system. Each calculator has
        a slug that can be used to access it directly.
      parameters:
      - name: name
        in: query
        enum:
        - desc
        - asc
        description: "Sort by name:\n * `desc` \n * `asc` \n "
        required: false
        default: asc
        schema:
          type: enum
      responses:
        '200':
          description: successful
  "/diaper_calculators":
    post:
      summary: Calculate diaper usage
      tags:
      - Diaper Calculator
      description: Calculate diaper usage based on user input
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      money_spent:
                        type: string
                        example: '31093.5'
                      money_will_be_spent:
                        type: string
                        example: '12220.7'
                      used_diapers_amount:
                        type: number
                        example: 3477
                      to_be_used_diapers_amount:
                        type: number
                        example: 1098
                      used_diapers_amount_pluralize:
                        type: string
                        example: already used
                      to_be_used_diapers_amount_pluralize:
                        type: string
                        example: to be used in the future
                  date:
                    type: integer
                    example: 18
                  text_products_to_be_used:
                    type: string
                    example: 1098.0 to be used in the future
                  text_products_used:
                    type: string
                    example: 3477.0 already used
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: Please, select years and months
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                childs_years:
                  type: integer
                  example: 1
                  description: Age in years (0-3)
                childs_months:
                  type: integer
                  example: 6
                  description: Age in months (0-11)
                category_id:
                  type: integer
                  example: 1
                  description: Category ID
              required:
              - childs_years
              - childs_months
              - category_id
  "/pad_calculators":
    post:
      summary: Pad calculator
      tags:
      - Pad Calculator
      description: |-
        Calculate pad usage and cost based on user input.
              Available categories: budget, average, premium
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  already_used_products:
                    type: integer
                    example: 2210
                    description: Already used products
                  already_used_products_cost:
                    type: integer
                    example: 4420
                    description: Already used products cost
                  products_to_be_used:
                    type: integer
                    example: 2600
                    description: Products to be used
                  products_to_be_used_cost:
                    type: integer
                    example: 5200
                    description: Products to be used cost
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      user_age:
                        type: string
                        example: Your age is missing
                      menstruation_age:
                        type: string
                        example: Age at First Menstruation must be in range from 1
                          to 100
                      menopause_age:
                        type: string
                        example: Age at Menopause is missing
                      average_menstruation_cycle_duration:
                        type: string
                        example: Average Menstrual Cycle Duration (days) is missing
                      pads_per_cycle:
                        type: string
                        example: Average Products Used Per Cycle is missing
                      pad_category:
                        type: string
                        example: Product Category is missing
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_age:
                  type: integer
                  example: 30
                  description: User age
                menstruation_age:
                  type: integer
                  example: 13
                  description: Menstruation age
                menopause_age:
                  type: integer
                  example: 50
                  description: Menopause age
                average_menstruation_cycle_duration:
                  type: integer
                  example: 28
                  description: Average menstruation cycle duration
                pads_per_cycle:
                  type: integer
                  example: 10
                  description: Pads per cycle
                pad_category:
                  type: string
                  example: budget
                  description: Pad category
              required:
              - user_age
              - menstruation_age
              - average_menstruation_cycle_duration
              - pads_per_cycle
servers:
- url: "{protocol}://{defaultHostLocal}/{locale}/api/v2/"
  description: Localhost server (uses test data)
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    defaultHostLocal:
      default: 127.0.0.1:3000
    locale:
      default: en
      enum:
      - en
      - uk
- url: "{protocol}://{defaultHostGlobal}/{locale}/api/v2/"
  description: Production server (uses live data)
  variables:
    protocol:
      default: https
      enum:
      - http
      - https
    defaultHostGlobal:
      default: calc.zerowastelviv.org.ua
    locale:
      default: en
      enum:
      - en
      - uk
