---
- name: Ensure Homebrew is installed
  shell: |
    /bin/bash -c "$(curl -fsSl https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  become: false
  
- name: Install Redis stack
  shell: |
    brew tap redis-stack/redis-stack
  become: false

- name: Install Redis
  shell: |
    brew install redis-stack
  become: false

- name: export redis PATH
  shell: |
    export PATH=/opt/homebrew/Caskroom/redis-stack-server/7.4.0-v2/bin:$PATH

- name: Start redis server
  shell: |
    redis-stack-server

