---
ruby_version: "3.3.5"
rails_version: "7.1.2"
bundler_version: "2.2.8"
puma_version: "5.6.9"
ruby_install_rails: true
ruby_install_from_source: true
ruby_install_bundler: true
ruby_install_puma: true
ruby_install_gems_development: true
ruby_install_gems_user: root
ruby_packages:
  - ruby-full
  - ruby-dev
  - build-essential
  - autogen
  - autoconf
  - libtool
  - nodejs
  - yarn
  - libvips
  - zlib1g-dev
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm-dev
  - libpq-dev
rvm_dependencies:
  - curl
  - gnupg
  # - build-essential
  # - libssl-dev
  # - libyaml-dev
  - libreadline-dev
  # - zlib1g-dev
  - libsqlite3-dev
  - sqlite3
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - software-properties-common
  # - libffi-dev
  # - nodejs
  # - yarn
ruby_rubygems_package_name: rubygems
ruby_download_url: https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.5.tar.xz
workspace: /root
ruby_source_configure_command: ./configure --enable-shared
# ruby_install_gems:
#   - name: "mutex_m"
#     version: "0.1.2"
#   - name: "cancancan"
#     version: "~> 3.3"
#   - name: "jbuilder"
#     version: "~> 2.7"
#   - name: "kaminari"
#     version: null
#   - name: "pg"
#     version: "~> 1.1"
#   - name: "rails"
#     version: "7.1.2"
#   - name: "redis"
#     version: "~> 4.0"
#   - name: "puma"
#     version: "5.0"
#   - name: "sass-rails"
#     version: ">= 6"
#   - name: "hotwire-rails"
#     version: null
#   - name: "bootstrap"
#     version: null
#   - name: "importmap-rails"
#     version: "~> 1.1"
#   - name: "image_processing"
#     version: "1.2"
#   - name: "mini_magick"
#     version: "4.9.5"
#   - name: "dotenv-rails"
#     version: null
#   - name: "rspec-rails"
#     version: null
#   - name: "acts_as_singleton"
#     version: null
#   - name: "friendly_id"
#     version: "~> 5.4.0"
#   - name: "babosa"
#     version: null
#   - name: "dentaku"
#     version: "~> 3.1"
#   - name: "net-smtp"
#     version: null
#   - name: "country_select"
#     version: null
#   - name: "bigdecimal"
#     version: "3.0.2"
#   - name: "rails-i18n"
#     version: "~> 7.0.0"
#   - name: "bootsnap"
#     version: null
#   - name: "tailwindcss-rails"
#     version: "~> 2.0"
#   - name: "active_storage_validations"
#     version: null
#   - name: "font-awesome-sass"
#     version: "~> 6.4"
#   - name: "factory_bot_rails"
#     version: null
############
rvm1_install_path: "~/.rvm"
rvm1_rvm: "{{ rvm1_install_path }}/bin/rvm"
rvm1_temp_download_path: "/tmp"
rvm1_rvm_latest_installer: "https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer"
rvm1_gpg_keys: "409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"
rvm1_gpg_key_server: "hkp://keys.openpgp.org"
rvm1_gpg_key_servers:
  - "{{ rvm1_gpg_key_server }}"
  - hkp://pgp.mit.edu
  - hkp://keyserver.pgp.com
  - hkp://keyserver.ubuntu.com
rvm1_rvm_version: "stable"
rvm1_install_flags: "--auto-dotfiles --user-install"
rvm1_autolib_mode: 3
rvm1_ruby_install_flags:
rvm1_rubies:
  - "ruby-3.3.5"
rvm1_default_ruby_version: "{{ rvm1_rubies | last if rvm1_rubies and rvm1_rubies is iterable else rvm1_rubies }}"
rvm1_bundler_install: True
rvm1_symlink_to: "/usr/local/bin"
root_user: "root"
root_group: "{{ root_user }}"
rvm1_symlink_binaries:
  - "erb"
  - "executable-hooks-uninstaller"
  - "gem"
  - "irb"
  - "rake"
  - "rdoc"
  - "ri"
  - "ruby"
rvm1_symlink_bundler_binaries:
  - "bundle"
  - "bundler"
rvm1_delete_ruby:
rvm1_rvm_check_for_updates: True
