---
ruby_version: "3.3.5"
rails_version: "7.1.2"
ruby_packages:
  - build-essential
  - zlib1g-dev
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm-dev
