name: CD

on:
  workflow_run:
    workflows:
      - Rspec
    types:
      - compleed

  pull_request:
    branches:
      - develop
      - master
    types:
      - closed

  release:
    types:
      - published

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - name: Set up Unlighthouse Scan
        run: npm install -g @unlighthouse/cli puppeteer

      - uses: miloserdow/capistrano-deploy@v3
        with:
          target: staging
          deploy_key: ${{ secrets.STAGING_KEY_PASSWORD }}
          enc_rsa_key_pth: config/credentials/staging_deploy_id_ed25519_enc

      - name: Unlighthouse Assertions and Client
        run: unlighthouse-ci --site http://51.44.25.104/en --build-static --output-path .unlighthouse/dist

      - name: Make convert_json_to_csv executable
        run: chmod +x bin/convert_json_to_csv.rb

      - name: Convert JSON to CSV
        run: bin/convert_json_to_csv.rb .unlighthouse/dist/ci-result.json .unlighthouse/dist/ci-result.csv

      - name: Upload Unlighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse-report
          path: .unlighthouse/dist/**

  deploy-to-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - uses: miloserdow/capistrano-deploy@v3
        with:
          target: production
          deploy_key: ${{ secrets.PRODUCTION_KEY_PASSWORD }}
          enc_rsa_key_pth: config/credentials/production_deploy_id_ed25519_enc
