name: Production

on:
  workflow_run:
    workflows:
      - Rspec
    types:
      - completed

  release:
    types:
      - published

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - uses: miloserdow/capistrano-deploy@v3
        with:
          target: production
          deploy_key: ${{ secrets.PROD_DEPLOY_KEY }}
