name: Staging

on:
  workflow_run:
    workflows:
      - Rspec

  branches:
    - develop
  types:
    - closed

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - uses: miloserdow/capistrano-deploy@v3
        with:
          target: staging
          deploy_key: ${{ secrets.STAGING_KEY_PASSWORD }}
          enc_rsa_key_pth: config/credentials/staging_deploy_id_ed25519_enc
